name: Debug Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create SSH Key
        run: |
          echo "${{ secrets.ONE_CLICK_DEPLOY_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          echo "✅ SSH key created"

      - name: Debug SSH Key
        run: |
          ls -la private_key.pem
          file private_key.pem
          cat private_key.pem | head -n 5

      - name: Test SSH Connection
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.ONE_CLICK_DEPLOY_SSH_HOST }} "echo 'SSH Connection Successful!'"
