name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
          

      #Copiar código para servidor
      - name: copy file via ssh to server
        uses: appleboy/scp-action@master
        with:
          host: "ec2-3-22-242-130.us-east-2.compute.amazonaws.com"
          username: "ec2-user"
          key: ${{ secrets.ONE_CLICK_DEPLOY_SSH_KEY }}
          port: 22
          source: ".,!node_modules"
          target: "/usr/share/calc/api"
