name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x

      - name: Debug loaded variables (optional)
        run: |
          echo "Host: ${{ secrets.ONE_CLICK_DEPLOY.SSH_HOST }}"
          echo "Port: ${{ secrets.ONE_CLICK_DEPLOY.SSH_PORT }}"
          echo "Target: $SSH_TARGET"
          # Note: Não exiba chaves privadas em produção!

      # Copiar código para servidor
      - name: Copy files via SSH to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ONE_CLICK_DEPLOY.SSH_HOST }}
          username: ${{ secrets.ONE_CLICK_DEPLOY.SSH_USER }}
          key: ${{ secrets.ONE_CLICK_DEPLOY.SSH_KEY }}
          port: ${{ secrets.ONE_CLICK_DEPLOY.SSH_PORT }}
          source: ".,!node_modules"
          target: "/home/ec2-user/applications/production/calc-kcl"
