name: CI

on:
  push:
    branches: [ master ]

env:
  ENCODED_PIPELINE_SECRET: ${{ secrets.ONE_CLICK_DEPLOY }}

jobs:
  secrets:
    name: Accessing JSON secret
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Envs Before
        run: echo "Env values before"
        
      - name: Decode Secrets
        run: |
          if [ ! -x "$(command -v jq)" ]; then
            echo "jq not found, installing..."
            sudo apt-get update
            sudo apt-get install -y jq
          fi
                
  build:
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v2
        
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.5
          with:
            node-version: 16.x
          
        #Instalar as dependências NPM/YARN
        - name: Install dependencies
          run: yarn
  
        #Executar a build
        - name: Run Build
          run: yarn build
  
        #Copiar código para servidor
        - name: copy file via ssh to server
          uses: appleboy/scp-action@master
          with:
            host: ${{ env.SSH_HOST }}
            username: ${{ env.SSH_USER }}
            key: ${{ env.SSH_KEY }}
            port: ${{ env.SSH_PORT }}
            source: ".,!node_modules"
            target: "/usr/share/nginx/multfluxo/api"
        
        - name: Run production scripts
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_KEY }}
            port: ${{ secrets.SSH_PORT }}
            script: | 
              cd /usr/share/nginx/multfluxo/api
              yarn
              ./node_modules/.bin/typeorm migration:run
              pm2 restart api
