name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x

      #Copiar código para servidor
      - name: copy file via ssh to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ one_click_deploy_secrets.SSH_HOST }}
          username: ${{ one_click_deploy_secrets.SSH_USER }}
          key: ${{ one_click_deploy_secrets.SSH_KEY }}
          port: ${{ one_click_deploy_secrets.SSH_PORT }}
          source: ".,!node_modules"
          target: "/home/ec2-user/applications/production/calc-kcl"
